### ISSUE TITLE
Feature request: RES night mode support

### ISSUE THREAD

**Issue by ElijahPepe** [ElijahPepe/starterpack#3]
Adding night mode support to RES is, troublesome to say the least. However, as someone who actively browses Reddit at night, reducing eye strain is something I want to achieve by the end of the year (I hope!).

This also means a new set of color standards and images.

**Comment by ElijahPepe** [comment]
[A new branch](https://github.com/ElijahPepe/starterpack/tree/nightmode) has been created and all changes will be mirrored to [/r/starterpackCSS](https://www.reddit.com/r/starterpackCSS/). Commits should go to that branch.

**Comment by voicedm** [comment]
Sure thing - RES Nightmode is used a lot. We should look into doing this. Currently, it doesnt actually look half bad, it just needs some fine tuning imo.

**Comment by ElijahPepe** [comment]
@voicedm Changes should be applied on the test subreddit per 4e141d8.

**Comment by voicedm** [comment]
Sure thing
